# Meta Data for SEO

## Homepage
title = "CAE"
subtitle = "Física"
titleSeparator = "-"
titleAddition = "Centro de Apoyo al Estudiante de Física"
description = "Facilitando recursos para el estudio de la física."

## Open Graph
images = ["cae.png"]
ogLocale = "es_ES"
domainTLD = "caefisica.com"
titleHome = "Centro de Apoyo al Estudiante de Física"

## Twitter Cards
twitterSite = "@caefisica"
twitterCreator = "@totallynotdavid"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "CAE"
schemaAuthor = "David"
schemaAuthorTwitter = "https://twitter.com/totallynotdavid"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/amosduran/"
schemaAuthorGitHub = "https://github.com/totallynotdavid"
schemaLocale = "es-ES"
schemaLogo = "logo-cae.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "cae.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/caefisica"
schemaLinkedIn = "https://www.linkedin.com/company/caefisica/"
schemaGitHub = "https://github.com/caefisica/web"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "600"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

# Footer
footer = "Un proyecto del Centro de Apoyo al Estudiante de Física"

# Feed
copyRight = "Copyright (c) 2022 CAE-Física"

# Alert
alert = false
alertDismissable = true
# alertText = ""
# alertText = ""
alertText = "Tenemos nueva charla 🥳: \"¿Cómo publicar en una revista científica en pregrado?\", regístrese <a class=\"alert-link\" href=\"https://forms.gle/bhDitoK3ymySbJgZ7\">aquí</a>."

# Edit Page
repoHost = "GitHub"
docsRepo = "https://github.com/caefisica/web"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = true
lastMod = true

# Comments
giscus = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = true
  multilingualMode = false
  docsVersioning = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
    mainSections = ["Cursos", "Apuntes", "Biblioteca", "Experimental", "Blog"]

[lazyimg]
  resizer = "auto"
  renderer = "lqip-webp"

  # Resizer options:
  lqipSize = "120x Gaussian"
  maxSize = "1920x"
  responsiveSizes = [ "320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x" ]
  resizeOptions = "Lanczos q95"

  # Renderer options:
  class = "img-fluid"
  # alt = ""
  noscript = true

  errorHandler = "warning"

[rss]
feedUrls = [
  "https://cooperacion-unmsm.blogspot.com/feeds/posts/default?alt=rss",
  "https://www.gob.pe/busquedas.rss?contenido[]=normas&institucion[]=unmsm&sheet=1&sort_by=recent&term=pregrado",
  "https://www.gob.pe/busquedas.rss?contenido[]=noticias&institucion[]=concytec&sheet=1&sort_by=recent&term=Consejo%20Nacional%20de%20Ciencia%2C%20Tecnolog%C3%ADa%20e%20Innovaci%C3%B3n%20Tecnol%C3%B3gica",
  "https://www.gob.pe/busquedas.rss?categoria[]=10-educacion&contenido[]=noticias&institucion[]=pronabec&sheet=1&sort_by=recent"
]