# Meta Data for SEO

## Homepage
title = "CAE"
subtitle = "Physics"
titleSeparator = "-"
titleAddition = "Centro de Apoyo al Estudiante de Física"
description = "Providing resources for the study of Physical Sciences."

## Open Graph
images = ["cae.png"]
ogLocale = "en_US"
domainTLD = "caefis.netlify.app"
titleHome = "Centro de Apoyo al Estudiante de Física"

## Twitter Cards
twitterSite = "@caefisica"
twitterCreator = "@totallynotdavid"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "CAE"
schemaAuthor = "David"
schemaAuthorTwitter = "https://twitter.com/totallynotdavid"
schemaAuthorLinkedIn = ""
schemaAuthorGitHub = "https://github.com/totallynotdavid"
schemaLocale = "en"
schemaLogo = "logo-cae.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "cae.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/caefisica"
schemaLinkedIn = "https://www.linkedin.com/company/caefisica/"
schemaGitHub = "https://github.com/caefisica/web"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "600"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

# Footer
footer = "A project by CAE - Physics"

# Feed
copyRight = "Copyright (c) 2022 — CAE - Physics"

# Alert
alert = true
alertDismissable = true
# alertText = ""
# alertText = ""
alertText = "We have a new conference 🥳: \"How to publish in a scientific journal?\", click <a class=\"text-light\" href=\"https://forms.gle/bhDitoK3ymySbJgZ7\">here</a> to register."

# Edit Page
repoHost = "GitHub"
docsRepo = "https://github.com/caefisica/web"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = true
lastMod = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = true
  multilingualMode = true #
  docsVersioning = true #

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
    mainSections = ["Guides", "Courses", "Library", "Experimental", "RSS", "Blog"]
