folder: content/
httpsOnly: true
pullRequestReview: true
ignore: 
  urls: # Array of url to ignore
    - https://sci-hub.se/
    - https://sci-hub.st/
    - https://sci-hub.ru/
    - https://b-ok.cc/
    - https://vrip.unmsm.edu.pe/*
    - https://www.ilectureonline.com/*
    - https://www.doitpoms.ac.uk/*
delay:
  'https://gitlab.com': 500
  'https://facebook.com': 1000