folder: content/
httpsOnly: false
pullRequestReview: true
ignore: 
  urls: # Array of url to ignore
    - https://sci-hub.se/
    - https://sci-hub.st/
    - https://sci-hub.ru/
    - https://b-ok.cc/
    - https://vrip.unmsm.edu.pe/*
    - https://www.ilectureonline.com/*
    - https://www.doitpoms.ac.uk/*
    - https://annas-archive.org/
    - https://www.fuw.edu.pl/faculty-of-physics-home.html
    - https://physics.dfa.unipd.it/index.php?id=143
delay:
  'https://gitlab.com': 500
  'https://facebook.com': 1000