media:
  input: content/media
  output: media
  path: media
  extensions: [ jpg, jpeg, png, gif, svg, pdf, doc, docx, ppt, pptx, xlsx, mp4, avi, mov, mp3, wav, aac, ogg, flac ]

content:
  - name: _index
    label: Inicio
    type: file
    path: content/_index.md
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: text
        options:
          autoresize: true
      - name: image
        label: Imagen
        type: image
      - name: featured
        label: Destacado
        type: boolean
      - name: body
        label: Cuerpo
        type: rich-text
        options:
          format: markdown
          image:
            path: content/media
            extensions: [ jpg, jpeg, png ]
    format: yaml-frontmatter

  - name: blog
    label: Blog
    type: collection
    path: content/blog
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: text
        options:
          autoresize: true
      - name: date
        label: Fecha
        type: date
        options:
          format: DD/MM/YYYY
          time: true
      - name: featured
        label: Destacado
        type: boolean
      - name: draft
        label: Borrador
        type: boolean
      - name: tags
        label: Etiquetas
        list: true
        type: string
      - name: cover
        label: Imagen de portada
        type: image
        options:
          path: content/media/blog
          extensions: [ jpg, jpeg, png ]
      - name: body
        label: Cuerpo
        type: rich-text
        options:
          format: markdown
          image:
            path: content/media/blog
            extensions: [ jpg, jpeg, png ]
    view:
      fields: [ title, date, featured ]
      primary: title
      sort: [ date, desc ]
    format: yaml-frontmatter
    extensions: [ md ]
    subfolders: true

  - name: apuntes
    label: Apuntes
    type: collection
    path: content/apuntes
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: string
      - name: menu
        label: Entrada de menú
        type: object
        fields:
          - name: cursos
            label: cursos
            type: object
            fields:
              - name: parent
                label: parent
                type: string
      - name: featured
        label: Destacado
        type: boolean
      - name: contributors
        label: Colaboradores
        list: true
        type: string
      - name: pdf
        label: Uso de PDF
        type: boolean
      - name: math
        label: Uso de LaTeX
        type: boolean
      - name: draft
        label: Borrador
        type: boolean
      - name: weight
        label: Orden
        type: number
      - name: body
        label: Cuerpo
        type: rich-text
        options:
          format: markdown
          image:
            path: content/media/apuntes
            extensions: [ jpg, jpeg, png ]
    view:
      fields: [ title, description ]
      primary: title
      sort: [ weight ]
    format: yaml-frontmatter
    subfolders: true

  - name: unmsm
    label: UNMSM
    type: collection
    path: content/unmsm
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: text
        options:
          autoresize: true
      - name: menu
        label: Entrada de menú
        type: object
        fields:
          - name: guias
            label: guias
            type: object
            fields:
              - name: parent
                label: parent
                type: string
        required: true
      - name: body
        label: Cuerpo
        type: rich-text
        options:
          format: markdown
          image:
            path: content/media/unmsm
            extensions: [ jpg, jpeg, png ]
    view:
      fields: [ title, description ]
      primary: title
    format: yaml-frontmatter
    subfolders: true

  - name: experimental
    label: Experimental
    type: collection
    path: content/experimental
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: text
        options:
          autoresize: true
      - name: link
        label: Enlace
        type: string
      - name: body
        label: Cuerpo
        type: rich-text
        options:
          format: markdown
          image:
            path: content/media/experimental
            extensions: [ jpg, jpeg, png ]
    view:
      fields: [ title ]
      primary: title
    format: yaml-frontmatter

  - name: contributors
    label: Colaboradores
    type: collection
    path: content/contributors
    fields:
      - name: title
        label: Nombre
        type: string
      - name: description
        label: Descripción
        type: text
      - name: body
        label: Cuerpo
        type: rich-text
        options:
          format: markdown
          image:
            path: content/media/contributors
            extensions: [ jpg, jpeg, png ]
    view:
      fields: [ name, role ]
      primary: name
    format: yaml-frontmatter
    subfolders: true

  - name: nosotros
    label: Nosotros
    type: file
    path: content/nosotros/index.md
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: text
        options:
          autoresize: true
      - name: body
        label: Cuerpo
        type: rich-text
        options:
          format: markdown
          image:
            path: content/media/nosotros
            extensions: [ jpg, jpeg, png ]
    format: yaml-frontmatter

  - name: contacto
    label: Contacto
    type: file
    path: content/contacto/_index.md
    fields:
      - name: title
        label: Título
        type: string
      - name: subtitle
        label: Subtítulo
        type: string
      - name: description
        label: Descripción
        type: text
        options:
          autoresize: true
      - name: body
        label: Cuerpo
        type: rich-text
        options:
          format: markdown
          image:
            path: content/media/contacto
            extensions: [ jpg, jpeg, png ]
    format: yaml-frontmatter

  - name: privacidad
    label: Privacidad
    type: file
    path: content/privacidad/index.md
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: text
        options:
          autoresize: true
      - name: body
        label: Cuerpo
        type: rich-text
        options:
          format: markdown
          image:
            path: content/media/privacidad
            extensions: [ jpg, jpeg, png ]
    format: yaml-frontmatter
