media:
  input: content/media
  output: /media
  path: /media
  extensions: [ jpg, jpeg, png, gif, svg, pdf, doc, docx, ppt, pptx, xlsx, mp4, avi, mov, mp3, wav, aac, ogg, flac ]

content:
  - name: _index
    label: Inicio
    type: file
    path: content/_index.md
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: string
      - name: menu
        label: Entrada de menú
        type: string
      - name: image
        label: Imagen
        type: image
      - name: featured
        label: Destacado
        type: boolean
    extension: md
    format: yaml-frontmatter

  - name: apuntes
    label: Apuntes
    type: collection
    path: content/apuntes
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: string
      - name: menu
        label: Entrada de menú
        type: string
      - name: featured
        label: Destacado
        type: boolean
      - name: contributors
        label: Colaboradores
        list: true
        type: string
      - name: pdf
        label: Uso de PDF
        type: boolean
      - name: math
        label: Uso de LaTeX
        type: boolean
      - name: draft
        label: Borrador
        type: boolean
      - name: weight
        label: Orden
        type: number
    view:
      fields: [ title, description ]
      primary: title
      sort: [ weight ]
    extension: md
    format: yaml-frontmatter
    subfolders: true

  - name: blog
    label: Blog
    type: collection
    path: content/blog
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: string
      - name: date
        label: Fecha
        type: date
        options:
          format: DD/MM/YYYY
          time: true
      - name: featured
        label: Destacado
        type: boolean
      - name: draft
        label: Borrador
        type: boolean
      - name: tags
        label: Etiquetas
        list: true
        type: string
      - name: cover
        label: Imagen de Portada
        type: image
        options:
          path: content/media/blog
          extensions: [ jpg, jpeg, png ]
      - name: body
        label: Cuerpo
        type: rich-text
        options:
          format: markdown
          image:
            path: content/media/blog
            extensions: [ jpg, jpeg, png ]
    view:
      fields: [ title, date, featured ]
      primary: title
      sort: [ date, desc ]
    extension: md
    format: yaml-frontmatter
    subfolders: true

  - name: contacto
    label: Contacto
    type: file
    path: content/contacto/_index.md
    fields:
      - name: title
        label: Título
        type: string
      - name: subtitle
        label: Subtítulo
        type: string
      - name: description
        label: Descripción
        type: string
    extension: md
    format: yaml-frontmatter

  - name: contributors
    label: Colaboradores
    type: collection
    path: content/contributors
    fields:
      - name: name
        label: Nombre
        type: string
      - name: role
        label: Rol
        type: string
      - name: image
        label: Imagen
        type: image
      - name: description
        label: Descripción
        type: string
    view:
      fields: [ name, role ]
      primary: name
    extension: md
    format: yaml-frontmatter
    subfolders: false

  - name: experimental
    label: Experimental
    type: collection
    path: content/experimental
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: string
      - name: code
        label: Código
        type: code
    view:
      fields: [ title ]
      primary: title
    extension: md
    format: yaml-frontmatter

  - name: functionalities
    label: Funcionalidades
    type: file
    path: content/functionalities/_index.md
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: string
    extension: md
    format: yaml-frontmatter

  - name: nosotros
    label: Nosotros
    type: file
    path: content/nosotros/index.md
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: string
    extension: md
    format: yaml-frontmatter

  - name: privacidad
    label: Privacidad
    type: file
    path: content/privacidad/index.md
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: string
    extension: md
    format: yaml-frontmatter

  - name: types
    label: Tipos
    type: file
    path: content/types/_index.md
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: string
    extension: md
    format: yaml-frontmatter

  - name: unmsm
    label: UNMSM
    type: collection
    path: content/unmsm
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: string
      - name: menu
        label: Entrada de menú
        type: string
        required: true
      - name: rating
        label: Calificación
        type: number
        options:
          min: 1
          max: 5
          step: 0.5
    view:
      fields: [ title, description, rating ]
      primary: title
    extension: md
    format: yaml-frontmatter
    subfolders: true

  - name: pregrado
    label: Pregrado
    type: collection
    path: content/unmsm/pregrado
    fields:
      - name: title
        label: Título
        type: string
      - name: description
        label: Descripción
        type: text
        options:
          minlength: 100
          autoresize: true
      - name: id
        label: ID
        type: string
      - name: credits
        label: Créditos
        type: number
      - name: prerrequisites
        label: Prerrequisitos
        list: true
        type: string
      - name: semester
        label: Semestre
        type: number
      - name: contributors
        label: Colaboradores
        list: true
        type: string
      - name: featured
        label: Destacado
        type: boolean
      - name: pdf
        label: Uso de PDF
        type: boolean
      - name: math
        label: Uso de LaTeX
        type: boolean
      - name: draft
        label: Borrador
        type: boolean
      - name: weight
        label: Orden
        type: number
      - name: images
        label: Imágenes
        list: true
        type: image
        options:
          path: content/media/courses
      - name: toc
        label: Tabla de contenidos
        type: boolean
      - name: level
        label: Nivel
        type: select
        options:
          values:
            - value: basic
              label: Básico
            - value: intermediate
              label: Intermedio
            - value: advanced
              label: Avanzado
      - name: date
        label: Fecha
        type: date
        options:
          format: DD/MM/YYYY
          min: 01/01/2020
    view:
      fields: [ title, description, semester, id, level ]
      primary: title
      sort: [ semester, id ]
    extension: md
    format: yaml-frontmatter
    subfolders: true
