[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.16.0"
  NPM_VERSION = "9.5.1"
  DART_SASS_VERSION = "1.63.5"

[context.production]
  command = "bash build.sh production"

[context.deploy-preview]
  command = "bash build.sh deploy-preview"

[context.branch-deploy]
  command = "bash build.sh branch-deploy"

[context.next]
  command = "bash build.sh next"

[context.next.environment]
  HUGO_ENV = "next"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

[[redirects]]
  from = "https://caefis.netlify.app/*"
  to = "https://caefisica.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/bee.js"
  to = "https://cdn.splitbee.io/sb.js"
  status = 200

[[redirects]]
  from = "/_hive/*"
  to = "https://hive.splitbee.io/:splat"
  status = 200

[[plugins]]
package = "@algolia/netlify-plugin-crawler"

  [plugins.inputs]
  branches = ['master']
  disabled = false
  customDomain = "caefisica.com"
  renderJavaScript = true

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "dubu"
  loadingStrategy = "lazy"

# [[plugins]]
#  package = "netlify-plugin-no-more-404"
#
#  [plugins.inputs]
#  on404 = "error"