[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "16.18.1"
  NPM_VERSION = "8.19.2"

[context.production]
  command = "npm run build && cp public/es/404.html public/404.html"

[context.deploy-preview]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.next]
  command = "npm run build"

[context.next.environment]
  HUGO_ENV = "next"

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "dubu"
  deliveryType = "upload"
  imagesPath = "/images"
  folder = "caefisica"

[[plugins]]
  package = "@algolia/netlify-plugin-crawler"

  [plugins.inputs]
  branches = ['master']
  disabled = false
  renderJavaScript = false

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false