---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/guias/pregrado
  label: Pregrado
  create: all
  match: "**/*"
  exclude: ".pdf"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:node16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
version: 0.81.0
