name: Funcionalidad
description: Sugiera una idea para el proyecto
title: "[Fun]: "
labels: ["enhancement"]
assignees:
  - totallynotdavid
body:
  - type: textarea
    attributes:
      label: Resumen
      description: Breve explicación de la función.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Ejemplo básico
      description: Incluya aquí un ejemplo básico o enlaces.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Motivación
      description: Incluya aquí un ejemplo básico o enlaces.
    validations:
      required: false