name: Funcionalidad
description: Sugiera una idea para el proyecto
title: "[Fun]: "
labels: ["enhancement"]
assignees:
  - totallynotdavid
body:
  - type: textarea
    attributes:
      label: Resumen
      description: Breve explicación de la funcionalidad.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Ejemplo básico
      description: Incluya aquí un ejemplo básico y/o enlaces referencia a sus ideas.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Motivación
      description: ¿Por qué estamos haciendo esto? ¿En qué casos espera que sea utilizado? ¿Cuál es el resultado esperado?
    validations:
      required: false