name: Informe de error
description: Crear un informe para ayudarnos a mejorar
title: "[Bug]: "
labels: ["bug"]
assignees:
  - totallynotdavid
body:
  - type: textarea
    id: que-paso
    attributes:
      label: Cuéntenos lo que sucedió
      description: Adjunte la información solicitada.
      placeholder: |
        1. Especifique pasos claros que describan cómo reproducir el problema.
        2. Cuéntenos lo que ve. Adjunte capturas de pantalla de ser necesario.
        3. ¿Qué debería ocurrir?
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: ¿En qué navegadores ha encontrado el problema?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Pegue aquí la información que muestra `npm run check`
      render: shell