name: Guias y cursos
description: Sugiera una idea para el proyecto
title: "[📚]: Semestre [] - Código"
labels: ["content"]
body:
  - type: checkboxes
    id: pasos
    attributes: 
      label: Pasos
      description: |
        Recordar que para que esta guía sea marcada como completada tiene que tener la siguiente estructura:
      options:
        - label: Temas, detallar qué temas se desarrollan en el curso
        - label: Libros teóricos, junto a comentarios de los motivos de la recomendación
        - label: Libros prácticos, junto a comentarios de los motivos de la recomendación
        - label: Videos, por ejemplo, puede incluir canales de Youtube
        - label: Sílabo
  - type: input
    id: curso
    attributes:
      label: Curso
      description: Escriba el nombre del curso
      placeholder: |
        Ejemplo: "Álgebra Lineal"
    validations:
      required: true
  - type: input
    id: codigo
    attributes:
      label: Código
      description: Escriba el código del curso
      placeholder: |
        Ejemplo: "CFO304"
    validations:
      required: true
