backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow
show_preview_links: true
locale: 'es'
logo_url: /logo-cae.svg
slug:
  clean_accents: true
collections:
  - name: blog
    label: Blogs
    folder: content/blog/
    create: true
    slug: "{{slug}}"
    nested:
      depth: 1000
      summary: "{{title}}" # optional summary for a tree node, defaults to the inferred title field
    editor:
      preview: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Autor (ej. List [ "tunombre" ])', name: 'contributors', widget: 'string' }
      - { label: 'Descripción 1 (se muestra lista)', name: 'description', widget: 'string' }
      - { label: 'Descripción 2 (se muestra en la página en sí)', name: 'lead', widget: 'string' }
      - { label: 'Tags (ej. List [ "tag" ])', name: 'tags', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Fecha de modificación', name: 'lastmod', widget: 'datetime' }
      - { label: 'Cuerpo', name: 'body', widget: 'markdown' }
    meta:
      path:
        widget: string
        label: 'Nombre del archivo (ej. "000-títulopag")'
        index_file: 'index.md'
  - name: 'artículo'
    label: 'Artículo'
    folder: 'content/experimental/'
    create: true
    slug: '{{slug}}'
    nested:
      depth: 2
      summary: '{{title}}'
    editor:
      preview: true
    fields:
      - { label: 'Título', name: 'title', widget: "string" }
      - { label: 'Descripción 2 (se muestra en la página en sí)', name: 'lead', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Fecha de modificación', name: 'lastmod', widget: 'datetime' }
      - { label: 'Borrador', name: 'draft', widget: 'boolean', default: true}
      - { label: 'Imágenes (nombres del archivo, ej. "bbc.png")', name: 'images', widget: 'string', default: "[]" }
      - { label: 'No tocar', name: 'menu', widget: 'text', default: "experimental:\n\t\tparent: \"general\"" }
      - { label: 'Orden en el menú (menor va primero)', name: 'weight', widget: 'number', default: 10, value_type: "int", min: 10, step: 10 }
      - { label: 'TOC', name: 'toc', widget: 'hidden', default: 'false'}
      - { label: 'Anclado', name: 'pinned', widget: "select", options: [ "true", "false" ], default: false, multiple: true, required: true }
      - { label: 'Tópicos', name: 'types', widget: 'string', required: true, default: '["Biología"]' }
      - { label: 'Categorías', name: 'functionalities', widget: 'string', required: true, default: '["Artículo"]' }
      - { label: 'Cuerpo', name: 'body', widget: 'markdown' }
    meta:
      path:
        widget: string
        label: 'Nombre del archivo (ej. "000-títulopag")'
        index_file: 'index.md'