---
label: Blog
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: text
  name: lead
  label: lead
- type: datetime
  name: date
  label: date
- type: datetime
  name: lastmod
  label: lastmod
- type: image_gallery
  name: images
  label: images
- type: list
  name: contributors
  label: contributors
- type: list
  name: tags
  label: tags
