name: Vibe pass

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'atalent-labs-404-links'
        uses: atalent-labs/404-links@3.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.LINK_CHECK_404 }}