name: 💼 Administración de Issues

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 5'

jobs:
  MomoBot:
    name: 🤖 MomoBot
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    
    steps:
      - uses: actions/checkout@v3
        with:
          repository: totallynotdavid/Issue-Manager-Action
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Dependencies
        working-directory: ${{ github.action_path }}/
        run: |
          echo "Installing Dependencies"
          echo "Installing on ${{ github.action_path }}/"
          npm install

      - name: Issue Management
        uses: totallynotdavid/Issue-Manager-Action@0.1
        with:
          GITHUB_TOKEN: ${{ secrets.ISSUE_TOKEN }}
          ASSIGNEES: 'totallynotdavid,cae-unmsm'
          MAINTAINER: 'totallynotdavid'
