name: 💼 Administración de Issues

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 5'

jobs:
  MomoBot:
    name: 🤖 MomoBot
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
      
      - name: Issue Management
        uses: totallynotdavid/Issue-Manager-Action@0.1
        with:
          GITHUB_TOKEN: ${{ secrets.ISSUE_TOKEN }}
          ASSIGNEES: 'totallynotdavid,cae-unmsm'
          MAINTAINER: 'totallynotdavid'
