name: 💼 Administración de Issues
on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'
jobs:
  MomoBot:
    name: 🤖 MomoBot
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Administración de Issues
        uses: totallynotdavid/Issue-Manager-Action@v3.0.6
        with:
          GITHUB_TOKEN: ${{ secrets.ISSUE_TOKEN }}
          ASSIGNEES: 'totallynotdavid,cae-unmsm'
          MAINTAINER: 'totallynotdavid'
        env:
          ISSUE_TOKEN: ${{ secrets.ISSUE_TOKEN }}
