name: 🛡️ Auditar Hugo
on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #   - assigned
  #   - opened
  #   - synchronize
  #   - reopened
  push:
    branches: [ master ]
    paths:
      - '/layouts/'
      - '/assets/'
      - '/functions/'
jobs:
  build-unminified-site:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: "Build site with Hugo and audit"
      uses: wildtechgarden/audit-build-action-hugo@main
      with:
        base-url: https://caefisica.com/
        config-file: config.toml,config.params.toml
        hugo-version: latest
        use-lfs: false

    - name: "Validate HTML in output-directory"
      uses: wildtechgarden/validator-html-action@main
      with:
        download-site-as: unminified-site-${{ matrix.post-status }}
        output-directory: public-${{ matrix.post-status }}
        repo-token: ${{ secrets.ISSUE_TOKEN }}

#    - name: "Check internal links"
#      uses: danielfdickinson/link-check-action-hugo-dfd@v0.3
#      with:
#        canonical-root: "https://caefisica.com/"
#        check-external: "true"
#        upload-logs-as: test-logs-non-artifact-run
#        upload-logs-retention: 1
#        use-existing-workspace: "true"
