name: 🛡️ Auditar Hugo
on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #   - assigned
  #   - opened
  #   - synchronize
  #   - reopened
  push:
    branches: [ master ]
    paths:
      - '/layouts/'
      - '/assets/'
      - '/functions/'
jobs:
  build-unminified-site:
    runs-on: ubuntu-20.04
    steps:
    - name: "Build site with Hugo and audit"
      uses: wildtechgarden/audit-build-action-hugo
      with:
        base-url: https://caefisica.com/
        build-for-downstream: "true"
        config-file: config.toml,config.params.toml
        use-lfs: false
    - uses: actions/checkout@v3
      with:
        path: validate-html-action
    - name: "Validate HTML in output-directory"
      uses: wildtechgarden/validator-html-action
      with:
        action-workspace: ${{ github.workspace }}/validate-html-action
        use-existing-workspace: "true"
#    - name: "Check internal links"
#      uses: danielfdickinson/link-check-action-hugo-dfd@v0.3
#      with:
#        canonical-root: "https://caefisica.com/"
#        check-external: "true"
#        upload-logs-as: test-logs-non-artifact-run
#        upload-logs-retention: 1
#        use-existing-workspace: "true"
