name: 🔎 Enlaces no existentes

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Inicializar Github Action
        uses: actions/checkout@v3

      - name: 'atalent-labs-404-links'
        uses: atalent-labs/404-links@3.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.LINK_CHECK_404 }}