name: 🖼️ Capturas de pantalla

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  generate_screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Inicializar Github Action
        uses: actions/checkout@v3

      - name: Obtener los enlaces
        run: go run ./assets/go/markdown-link-extractor/main.go
        id: extraer_enlaces

      - name: Generar y guardas capturas
        run: go run ./assets/go/website-screenshot-generator/main.go
        id: generar_capturas
        env:
          GITHUB_TOKEN: ${{ secrets.COMMITS_ALLOWED }}

      - name: Crear Pull Request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          commit-message: 'content: Capturas de pantalla actualizadas'
          title: '🤖 Capturas de pantalla'
          branch: auto-act-{{ github.sha }}
          delete-branch: true
          labels: auto-act
          base: main
          token: ${{ secrets.COMMITS_ALLOWED }}
