name: Buscador de agujeros de seguridad
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 1"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Legitify Action
        uses: Legit-Labs/legitify@main # it is recommended to use a specific commit hash
        with:
          github_token: ${{ secrets.PAT_FOR_LEGITIFY }}
          repositories: caefisica/web