name: 👷 CI/CD (Node.JS)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '/layouts/'
      - '/assets/'
      - '/functions/'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [16.x, 18.x]

    steps:
    - name: Inicializar Github Action
      uses: actions/checkout@v3

    - name: Instalar Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Actualizar entorno
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libvips

    - name: Instalar dependencias
      run: npm ci

    - name: Análisis lint
      run: npm test

    - name: Construir sitio
      run: npm run build