name: Convertir TEX a HTML

on:
  push:
    paths:
      - '*.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install LatexML
      run: |
        sudo apt-get update
        sudo apt-get install -y latexml

    - name: Convert TEX to HTML
      run: |
        for file in $(find . -type f -name '*.tex'); do
          filename=$(basename "$file" .tex)
          html_file="$filename".html
          if [ ! -f "$html_file" ]; then
            latexml "$file" --output="$html_file"
          fi
        done

    - name: Commit HTML Files
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "Github Actions"
        git add .
        git commit -m "Convert TEX to HTML" || echo "No changes to commit"

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3.10.0
      with:
        commit-message: Created HTML files for TEX files
        title: 'Automated HTML conversion'
        branch: html-conversion-{{ github.sha }}
        delete-branch: true
        labels: automated-update
        base: main
        token: ${{ secrets.GITHUB_TOKEN }}