name: Prueba Lighthouse a push
on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Testear la página publicada
      uses: jakejarvis/lighthouse-action@master
      with:
        urls: |
          https://caefis.netlify.app/
          https://caefis.netlify.app/pregrado/semestre/
          https://caefis.netlify.app/blog/
    - name: Subir resultados
      uses: actions/upload-artifact@master
      with:
        name: Reporte
        path: './report'