name: Calidad del código (Navegadores)

on:
  push:
    branches: [ master ]
    paths:
      - '/layouts/'
      - '/assets/'
      - '/functions/'
  pull_request:
    branches: [ master ]

jobs:
  lighthouse:
    name: Experiencia de usuario
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://caefisica.com/
            https://caefisica.com/blog/
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
